server:
  port: 8002

spring:
  application:
    name: cloud-comsumer-order80

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    register-with-eureka: true
    fetch-registry: true
